### ISSUE TITLE
Is there some script examples for deleting task and reports of openvas?

### ISSUE THREAD

**Issue by yldiscover** [greenbone/gvm-tools#263] opened 2020-05-14 03:52 UTC
Hi,
   Could you tell me, is there some script examples for deleting task and reports of openvas?

   We have set many tasks and got many reports, and we need to delete them in batch mode.

   But the github provided script examples only show how to setup task, but no deleting task.

**Comment by bjoernricks** [comment] 2020-05-14 06:57
Hi,

this is a support question which belongs to https://community.greenbone.net/ and not a bug in our software. Therefore I am closing this ticket.

* There are a lot of example scripts in gvm-tools.
* The API of gvm-tools is provided by [python-gvm](https://github.com/greenbone/python-gvm)
* Both tools have an extensive documentation
* If there is `gmp.get_tasks`, `gmp.create_task`, `gmp.clone_task` what do you think what is the name of the delete API? Right [`gmp.delete_task`](https://python-gvm.readthedocs.io/en/latest/api/gmpv7.html#gvm.protocols.gmpv7.Gmp.delete_task). I really think our API is straight forward.

**Closed by bjoernricks** 2020-05-14 06:57 UTC
Labels: invalid

**Comment by yldiscover** [comment] 2020-05-15 09:16
Hi, I have tried the  gmp.delete_task api to delete tasks, and the reports have been deleted too. That is what I want. Thanks!
